discussion/urls.py
from django.urls import path, include
from .views import discussion_home_view, dynamic_post_view, delete_post_view, delete_reply_view

urlpatterns = [
    path("", discussion_home_view, name="discussion_home"),
    path("<int:id>/", dynamic_post_view, name="dynamic_post"),
    path("<int:id>/delete", delete_post_view, name="delete_post"),
    path("<int:rid>/delete_reply", delete_reply_view, name="delete_reply")
]

innovators/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # added by shubham
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("userprofile.urls")),
    path("schemes/", include("schemes.urls")),
    path('gtts/', include('gTTS.urls')),
    # for user authorized dynamic translation
    path('gtts_auth/', include('gTTS.urls_auth')),
    # path('verification/', include('verify_email.urls')),	# email verification
    # for discussion
    path('discussion/', include("discussion.urls")),
]

schemes/urls.py
from django.urls import path, include
from .views import all_schemes_view, user_schemes_view, dynamic_scheme_view,catagory_scheme_view

urlpatterns = [
    path("", all_schemes_view, name="all_schemes"),
    path("user_schemes/", user_schemes_view, name="user_schemes"),
    path("<int:id>/", dynamic_scheme_view, name="dynamic_scheme"),
    path("<str:cat>/",catagory_scheme_view,name="catagory_schemes")
]

discussion/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    description = models.TextField(max_length=10000)

    class Meta:
        db_table = "post"

    def __str__(self) -> str:
        return self.title


class Reply(models.Model):
    user = models.ForeignKey(
        User, null=True, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    description = models.TextField(max_length=5000)

    class Meta:
        db_table = "reply"

    def __str__(self) -> str:
        return self.description

discussion/forms.py
from .models import Post, Reply
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description')
        widgets = {
            'title': forms.TextInput(attrs={"class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"}),
            'description': forms.Textarea(attrs={"class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"})
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('description',)
        widgets = {
            'description': forms.Textarea(attrs={"class": "text-gray-800 border-2 border-gray-700 rounded-lg focus:outline-none block w-[95%] mr-2 py-1.5", "rows": "4"})
        }

discussion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Reply
from django.views.generic import ListView
from .forms import PostForm, ReplyForm
from django.contrib import messages


@login_required(login_url="login")
def discussion_home_view(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        post = form.save(commit=False)
        user = request.user
        post.user = user
        print(post.user.username)
        print(post.title)
        print(post.description)
        post.save()
        return redirect("discussion_home")
    else:
        form = PostForm()
    context = {
        'form': form
    }
    all_posts = Post.objects.all()
    # all_posts.entry_set.all()
    context["all_posts"] = all_posts
    return render(request, "discussion_home.html", context)


@login_required(login_url="login")
def dynamic_post_view(request, id):
    if request.method == "POST":
        form = ReplyForm(request.POST)
        reply = form.save(commit=False)
        user = request.user
        post = Post.objects.get(id=id)
        reply.user = user
        reply.post = post
        reply.save()
        return redirect("discussion_home")
    else:
        form = ReplyForm()
        obj = Post.objects.get(id=id)
    context = {
        "post": obj,
        "form": form
    }
    return render(request, "dynamic_post_view.html", context)


@login_required(login_url="login")
def delete_post_view(request, id):
    obj = Post.objects.get(id=id)
    if (obj.user == request.user):
        obj.delete()
        messages.success(request, "Post deleted")
        return redirect("discussion_home")
    else:
        messages.error(request, "You can only delete posts made by you")
        return redirect("discussion_home")


@login_required(login_url="login")
def delete_reply_view(request, rid):
    obj = Reply.objects.get(id=rid)
    if (obj.user == request.user):
        obj.delete()
        messages.success(request, "Post deleted")
        return redirect("discussion_home")
    else:
        messages.error(request, "You can only delete posts made by you")
        return redirect("discussion_home")

discussion/templates/discussion_home.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<!-- <section class="bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] fixed mt-12 flex justify-center w-full h-fit overflow-y-hidden">
  yay
</section> -->
{% if messages %}
<script>
    alert({% for message in messages %}<h3>{{ message }}</h3>{% endfor %})
</script>
{% endif %}
<script>
    let isModelHidden = true;
    let isScreenBlack = false;
    function showModel() {
        const model = document.getElementById("authentication-modal");
        if (isModelHidden) {
            model.style.display = "flex";
            isModelHidden = false;
            // showBlackScreen();
        } else {
            model.style.display = "none";
            isModelHidden = true;
            // showBlackScreen();
        }
    }
    function showBlackScreen() {
        const scr = document.getElementById("black");
        if (!isScreenBlack) {
            scr.style.display = "flex";
            isScreenBlack = true;
        } else {
            scr.style.display = "none";
            isScreenBlack = false;
        }
    }
</script>
<section id="black" class="absolute w-full z-[30] h-screen bg-black opacity-50" style="display: none">
</section>
<section
    class="w-full h-screen flex flex-col justify-center items-center bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] mt-12 fixed">
    <button onclick="showModel()" class="absolute z-50 bottom-[15%] right-16 fill-blue-700">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
            class="w-12 h-12 rounded-full bg-blue-500 border-2 border-gray-300 text-gray-300 p-1">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
    </button>
    <div id="authentication-modal" class="z-[60] w-1/4 h-1/2 p-4" style="display: none">
        <div class="relative w-full h-full max-w-md md:h-auto">
            <div class="relative bg-gray-100 rounded-lg shadow-2xl border border-black">
                <button type="button"
                    class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"
                    data-modal-hide="authentication-modal" onclick="showModel()">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd">
                        </path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
                <div class="px-6 py-6 lg:px-8">
                    <h3 class="mb-4 text-xl font-medium text-gray-900">Start new discussion</h3>
                    <form class="space-y-6" method="post">
                        {% csrf_token %}
                        <div>
                            <label for="email" class="block mb-2 text-sm font-medium text-gray-900">Title</label>
                            {{ form.title }}
                        </div>
                        <div>
                            <label for="description"
                                class="block mb-2 text-sm font-medium text-gray-900">Description</label>
                            {{ form.description }}
                        </div>
                        <button type="submit"
                            class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                            Done
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="flex fixed w-full h-3/4 flex-col justify-center items-center overflow-y-scroll">
        <div class="flex flex-col justify-center items-center space-y-6">
            {% for post in all_posts %}
            <a href=" {% url 'dynamic_post' post.id %}"
                class="mt-[50%] w-[75%] h-auto p-6 bg-gray-50 border border-gray-200 rounded-lg shadow-xl">
                <div class="flex space-x-2 mt-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                    <p class="font-bold font-lg">{{ post.user.username }}</p>
                </div>
                <h5 class="mb-2 text-2xl font-bold">{{ post.title }}</h5>
                <p class="font-normal text-gray-700">{{ post.description }}</p>
                {% if post.user == request.user %}
                <div class="flex w-full justify-between">
                    <div></div>
                    <form action="{% url 'delete_post' post.id %}">
                        <button type="submit"
                            class="text-red-600 border border-red-600 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-2.5 py-1 text-center">
                            Delete
                        </button>
                    </form>
                </div>
                {% endif %}
            </a>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

discussion/templates/dynamic_post_view.html
{% extends 'base.html' %}
{% block content %}
    {% include 'navbar.html' %}
    <!-- <section class="bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] fixed mt-12 flex justify-center w-full h-fit overflow-y-hidden">
  yay
</section> -->
    <script>
    let isModelHidden = true;
    let isScreenBlack = false;
    function showModel() {
        const model = document.getElementById("authentication-modal");
        if (isModelHidden) {
            model.style.display = "flex";
            isModelHidden = false;
            // showBlackScreen();
        } else {
            model.style.display = "none";
            isModelHidden = true;
            // showBlackScreen();
        }
    }
    function showBlackScreen() {
        const scr = document.getElementById("black");
        if (!isScreenBlack) {
            scr.style.display = "flex";
            isScreenBlack = true;
        } else {
            scr.style.display = "none";
            isScreenBlack = false;
        }
    }
    </script>
    <section id="black"
             class="absolute w-full z-[30] h-screen bg-black opacity-50"
             style="display: none">
    </section>
    <section class="w-full h-screen flex flex-col justify-center items-center bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] mt-12 fixed">
        <div class="flex items-center fixed w-full h-3/4 flex-col">
            <div class="w-[50%] bg-gray-50 h-auto rounded-xl shadow-xl mb-2 pb-2 overflow-y-auto">
                <div class="mx-6 space-y-4 ">
                    <div class="flex space-x-2 mt-6">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24"
                             stroke-width="1.5"
                             stroke="currentColor"
                             class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                            d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        <p class="font-bold font-lg">{{ post.user.username }}</p>
                    </div>
                    <div class="flex flex-col space-y-2">
                        <p class="font-normal text-3xl">{{ post.title }}</p>
                        <div class="w-full temp:w-full text-justify ">
                            <p class="font-normal text-lg">{{ post.description }}</p>
                        </div>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="flex flex-col">
                            {{ form.description }}
                            <div class="flex w-[95%] mt-2 justify-between">
                                <div></div>
                                <button type="submit"
                                        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-2.5 py-1 text-center">
                                    Comment
                                </button>
                            </div>
                        </div>
                    </form>
                    {% for reply in post.reply_set.all %}
                        <div class="ml-4 mr-8 space-y-1 mt-4 mb-4 border rounded-md p-4 shadow-lg border-b-gray-800 ">
                            <div class="flex">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     fill="none"
                                     viewBox="0 0 24 24"
                                     stroke-width="1.5"
                                     stroke="currentColor"
                                     class="w-6 h-6 mr-2">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                                </svg>
                                <p class="font-bold font-lg">{{ reply.user.username }}</p>
                            </div>
                            <p class="font-normal text-lg">{{ reply.description }}</p>
                            <div class="flex w-full justify-between">
                                <div></div>
                                {% if reply.user == request.user %}
                                    <form action="{% url 'delete_reply' reply.id %} ">
                                        <button type="submit"
                                                class="text-red-600 border border-red-600 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-2.5 py-1 text-center">
                                            Delete
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- 2nd -->
        </section>
    {% endblock content %}