innovators/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # added by shubham
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("userprofile.urls")),
    path("schemes/", include("schemes.urls")),
    path('gtts/', include('gTTS.urls')),
    # for user authorized dynamic translation
    path('gtts_auth/', include('gTTS.urls_auth')),
    # path('verification/', include('verify_email.urls')),	# email verification
    # for discussion
    path('discussion/', include("discussion.urls")),
]

schemes/urls.py
from django.urls import path, include
from .views import all_schemes_view, user_schemes_view, dynamic_scheme_view,catagory_scheme_view

urlpatterns = [
    path("", all_schemes_view, name="all_schemes"),
    path("user_schemes/", user_schemes_view, name="user_schemes"),
    path("<int:id>/", dynamic_scheme_view, name="dynamic_scheme"),
    path("<str:cat>/",catagory_scheme_view,name="catagory_schemes")
]

schemes/models.py
from email.policy import default
from random import choices
from django.db import models
import datetime
from datetime import date

# Create your models here.


class Scheme(models.Model):
    name = models.CharField(max_length=300, default="demo scheme", unique=True)
    scheme_info = models.TextField(max_length=500, default="empty")
    MARITAL_CHOICES = (
        ('single', 'Single'),
        ('married', 'Married'),
        ('widowed', 'Widowed'),
        ('divorced', 'Divorced'),
        ('any', 'any'),
    )
    marital_status = models.CharField(max_length=10,
                                      choices=MARITAL_CHOICES,
                                      default="any")
    AGE_CHOICES = (
        ('0-18', '0-18'),
        ('18-50', '18-50'),
        ('50-125', '50-125'),
        ('any', 'any')
    )
    age = models.CharField(default='any', choices=AGE_CHOICES, max_length=30)
    link = models.URLField(default="www.google.com")
    start_date = models.DateField(default=datetime.date.today)
    last_date = models.DateField(default=datetime.date.today)

    class Meta:
        db_table = 'scheme'

    def __str__(self):
        return self.name

    @property
    def is_past_due(self):
        return date.today() > self.last_date


class Genders(models.Model):
    scheme = models.ForeignKey(
        Scheme, on_delete=models.CASCADE)
    GENDER_CHOICES = (
        ('male', 'male'),
        ('female', 'female'),
        ('other', 'other'),
        ('any', 'any')
    )
    gender = models.CharField(
        max_length=30, choices=GENDER_CHOICES)

    class Meta:
        db_table = 'genders'
        unique_together = (('scheme', 'gender'))

    def __str__(self):
        return (self.scheme.name + " --> " + self.gender)


class Incomes(models.Model):
    scheme = models.ForeignKey(
        Scheme, on_delete=models.CASCADE)
    INCOME_CHOICES = (
        ('BPL', "Less Than 50000"),
        ('lower', "50000-250000"),
        ('middle', "250000-700000"),
        ('upper', 'Greater Than 700000'),
        ('any', 'any'),
    )
    # max_income_class = models.CharField(max_length=10,
    #                                     choices=INCOME_CHOICES,
    #                                     default="any")
    income = models.CharField(
        max_length=30, choices=INCOME_CHOICES)

    class Meta:
        db_table = 'incomes'
        unique_together = (('scheme', 'income'))


class Educations(models.Model):
    scheme = models.ForeignKey(
        Scheme, on_delete=models.CASCADE)
    EDUCATION_CHOICES = (
        ('primary', 'Primary education(till 8th class)'),
        ('secondary', 'Secondary education(till 10th class)'),
        ('senior_secondary', 'Senior Secondary education (till 12th class)'),
        ('undergraduate', ' Undergraduate education'),
        ('postgraduate', 'Postgraduate education'),
        ('any', 'any'),
    )
    education = models.CharField(
        max_length=30, choices=EDUCATION_CHOICES)

    class Meta:
        db_table = 'educations'
        unique_together = (('scheme', 'education'))


class Castes(models.Model):
    scheme = models.ForeignKey(
        Scheme, on_delete=models.CASCADE)
    CASTE_CHOICES = (
        ('general', 'general'),
        ('SC', 'SC'),
        ('ST', 'ST'),
        ('OBC', 'OBC'),
        ('any', 'any'),
    )
    caste = models.CharField(
        max_length=30, choices=CASTE_CHOICES)

    class Meta:
        db_table = 'castes'
        unique_together = (('scheme', 'caste'))


class Catagories(models.Model):
    scheme = models.ForeignKey(
        Scheme, on_delete=models.CASCADE)
    CATAGORY_CHOICES = (
        ('education', 'education'),
        ('startup', 'startup'),
        ('agriculture', 'agriculture'),
        ("other", "other"),
    )
    catagory = models.CharField(
        max_length=30, choices=CATAGORY_CHOICES)

    class Meta:
        db_table = 'catagories'
        unique_together = (('scheme', 'catagory'))


class Documents(models.Model):
    scheme = models.ForeignKey(Scheme, on_delete=models.CASCADE)
    DOCUMENT_CHOICES = (
        ('adhar_card', 'Adhar Card'),
        ('income_certificate', 'Income Certificate'),
        ('cast_certificate', 'Cast Certificate'),
        ('SSC_marksheet', 'SSC Marksheet'),
        ('leaving_certificate', 'Leaving Certificate'),
        ('PAN_card', 'PAN Card'),
        ('reservation_certificate', 'Reservation Certificate'),
        ('driving_licence', 'Driving Licence'),
        ('passport', 'Passport')
    )
    document = models.CharField(max_length=150, choices=DOCUMENT_CHOICES)

    class Meta:
        db_table = 'documents'
        unique_together = (('scheme', 'document'))

schemes/views.py
import datetime
from django.shortcuts import render
from .models import Scheme, Genders
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.db.models import Q
from googletrans import Translator
# Create your views here.
from django.utils import timezone
from gTTS.cache import remove_cache
from gtts import gTTS
from django.contrib import messages


def valid_age(age):
    if age in range(1, 19):
        return ("0-18")
    if age in range(19-51):
        return ("18-50")
    else:
        return ("50-125")


def all_schemes_view(request):
    remove_cache()
    all_schemes = Scheme.objects.all().order_by('catagories__catagory')
    context = {"schemes": all_schemes}
    # print(timezone.now())
    return render(request, "all_schemes.html", context)


@login_required(login_url="login")
def user_schemes_view(request):
    current_user = request.user
    if current_user.username == "admin":
        print("hi")
        messages.error(request, "admin can not have a profile")
        return redirect("home")
    # eligible_schemes = Scheme.objects.filter(Q(education='any'|education__contains=current_user.education_class),
    #                                         Q(caste_data="any" | caste_data__contains=current_user.cast_class))
    eligible_schemes = Scheme.objects.filter(
        (Q(genders__gender="any") | Q(genders__gender=current_user.profile.gender)),
        (Q(incomes__income="any") | Q(
            incomes__income=current_user.profile.income_class)),
        (Q(marital_status="any") | Q(marital_status=current_user.profile.marital_status)),
        (Q(age="any") | Q(age=valid_age(current_user.profile.age))),
        (Q(castes__caste="any") | Q(castes__caste=current_user.profile.cast_class)),
        (Q(educations__education="any") | Q(
            educations__education=current_user.profile.education_class))
    )
    context = {"schemes": eligible_schemes, "user": current_user}
    return render(request, "user_schemes.html", context)


def dynamic_scheme_view(request, id):
    remove_cache()
    # translator= Translator(to_lang="Hindi")
    tr = Translator()
    obj = Scheme.objects.get(id=id)
    if (obj.last_date < datetime.date.today()):
        my_string = "expired"
        print(my_string)
    else:
        my_string = "valid"

    # translating to hindi via google_translate library
    hi_data = tr.translate(obj.scheme_info, dest='hi').text
    # translation = translator.translate(obj.scheme_info)
    # print(translation)
    context = {
        "scheme": obj,
        "hi_data": hi_data,
        "validity": my_string,
    }
    return render(request, "dynamic_scheme_new.html", context)


def catagory_scheme_view(request, cat):
    cat_schemes = Scheme.objects.filter(catagories__catagory=cat)
    context = {"schemes": cat_schemes}
    return render(request, "user_schemes.html", context)

schemes/templates/all_schemes.html
{% extends 'base.html' %}
{% block content %}
    {% include 'navbar.html' %}
    {% include "scheme_table1.html" %}
{% endblock content %}

schemes/templates/dynamic_scheme.html
{% extends "base.html" %} 
{% block content %} 
{% include "navbar.html" %}

<script>
  var isPlaying = false;
  function pp() {
    var id = document.getElementById("player");
    if (isPlaying == true) {
      id.pause();
      isPlaying = false;
    } else {
      id.play();
      isPlaying = true;
      id.volume = 1.0;
    }
  }
</script>
<div
  class="flex justify-center w-full bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] h-fit"
>
  <div class="mt-36 w-full flex flex-col justify-start items-center">
    <div class="mb-6">
      <p class="text-center text-5xl font-[575]">{{ scheme.name }}</p>
    </div>
    <div
      class="mb-12 border-[1.5px] border-b-gray-800 border-t-transparent border-r-transparent border-l-transparent p-10 rounded-md w-3/4"
    >
      <p class="text-center text-xl" name="scheme_info" id="schemee_info">
        {{ scheme.scheme_info }}
      </p>
      {% load gTTS %}
      <audio
        src="{% say 'en-in' guj_data %}"
        class="hidden"
        id="player"
        controls
      ></audio>
      <div class="w-full flex justify-center cursor-pointer mt-6">
        <div
          class="text-white rounded-xl bg-blue-400 w-auto flex justify-center items-center ease-in-out px-4 py-2 font-normal text-base transition-all duration-[250ms] hover:bg-blue-700 hover:rounded-xl hover:text-white"
          onclick="pp()"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="w-6 h-6 mr-2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 18.75a6 6 0 006-6v-1.5m-6 7.5a6 6 0 01-6-6v-1.5m6 7.5v3.75m-3.75 0h7.5M12 15.75a3 3 0 01-3-3V4.5a3 3 0 116 0v8.25a3 3 0 01-3 3z"
            />
          </svg>
          <p className="cursor-pointer text-lg font-semibold">हिन्दी</p>
        </div>
      </div>
    </div>
    <div
      class="w-3/4 h-auto flex flex-col justify-evenly items-center border-t-transparent border-r-transparent border-l-transparent border-b-gray-800 border-[1.5px] mb-12 pb-4"
    >
    <div class="w-1/2 flex flex-col justify-center items-center">
      <div class="-mt-8 mb-4 flex justify-center w-full items-center">
        <p class="text-3xl font-semibold">
          Scheme's availability and official website
        </p>
      </div>
      <div class="flex w-3/4 justify-around">
        <div class="w-1/2 flex flex-col justify-center items-start">
          <div class="flex">
            <p class="text-lg font-semibold mr-1">
              Start date : 
            </p>
              <p class="text-lg">
                {{ scheme.start_date }}
              </p> 
          </div>
          <div class="flex">
            <p class="text-lg font-semibold mr-1">
              End date : 
            </p>
              <p class="text-lg">
                {{ scheme.last_date }}
              </p> 
          </div>
        </div>
          <div class="w-1/2 flex flex-col">
            <a href="{{ scheme.link }}" class="text-blue-600 underline text-xl mb-1"
              >Link to official website</a
            >
            {% if validity == "expired" %}
            <p class="text-lg text-left font-semibold text-red-600">
              The scheme has been expired
            </p>
            {% else %}
            <p class="text-lg text-left font-semibold text-green-600">
              The scheme can be availed
            </p>
            {% endif %}
        </div>
      </div>
    </div>
    </div>
    <div class="flex justify-between w-3/4 space-x-40">
      <div class="w-full h-auto">
        <div class="mb-10">
          <p class="text-4xl text-center">Eligibility critria</p>
        </div>
        <div class="rounded-lg border shadow-2xl">
          <table class="relative w-full border text-sm text-left text-black">
            <thead class="text-white">
              <tr>
                <th class="sticky top-0 py-3 px-6 bg-blue-600 text-md">Type</th>
                <th class="sticky top-0 py-3 px-6 bg-blue-600 text-md">
                  Value
                </th>
              </tr>
            </thead>
            <tbody>
              <tr class="border-b bg-blue-200">
                <th scope="row" class="py-4 px-6 font-medium">Age</th>
                <td class="py-4 px-6">{{ scheme.age }}</td>
              </tr>
              <tr class="border-b bg-blue-300">
                <th scope="row" class="py-4 px-6 font-medium">
                  Marital status
                </th>
                <td class="py-4 px-6">{{ scheme.marital_status }}</td>
              </tr>
              <tr class="border-b bg-blue-200">
                <th scope="row" class="py-4 px-6 font-medium">Income</th>
                <td class="py-4 px-6">
                  <ul>
                    {% for income in scheme.incomes_set.all %}
                    <li>{{ income.income }}</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              <tr class="border-b bg-blue-300">
                <th scope="row" class="py-4 px-6 font-medium">Education</th>
                <td class="py-4 px-6">
                  <ul>
                    {% for education in scheme.educations_set.all %}
                    <li>{{ education.education }}</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              <tr class="border-b bg-blue-200">
                <th scope="row" class="py-4 px-6 font-medium">Caste</th>
                <td class="py-4 px-6">
                  <ul>
                    {% for caste in scheme.castes_set.all %}
                    <li>{{ caste.caste }}</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              <tr class="border-b bg-blue-300">
                <th scope="row" class="py-4 px-6 font-medium">Gender</th>
                <td class="py-4 px-6">
                  <ul>
                    {% for gender in scheme.genders_set.all %}
                    <li>{{ gender.gender }}</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              <tr class="border-b bg-blue-300">
                <th scope="row" class="py-4 px-6 font-medium">Last Date</th>
                <td class="py-4 px-6">{{ scheme.last_date }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="w-full h-auto">
        <div class="mb-10">
          <p class="text-4xl text-center">Documents needed</p>
        </div>
        <div class="rounded-lg border shadow-2xl">
          <table class="relative w-full border text-sm text-left text-black">
            <thead>
              <tr>
                <th
                  class="sticky top-0 py-3 px-6 bg-blue-600 text-xs text-white uppercase"
                >
                  Documents
                </th>
              </tr>
            </thead>
            <tbody>
              <tr class="border-b bg-blue-200">
                <th scope="row" class="py-4 px-6 font-medium">
                  Caste cirtificate
                </th>
              </tr>
              <tr class="border-b bg-blue-300">
                <th scope="row" class="py-4 px-6 font-medium">
                  Income cirtificate
                </th>
              </tr>
              <tr class="border-b bg-blue-200">
                <th scope="row" class="py-4 px-6 font-medium">Aadhar card</th>
              </tr>
              <tr class="border-b bg-blue-300">
                <th scope="row" class="py-4 px-6 font-medium">PAN card</th>
              </tr>
              <tr class="border-b bg-blue-200">
                <th scope="row" class="py-4 px-6 font-medium">
                  Bonafied cirtificate
                </th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div
      class="w-3/4 mt-12 h-fit py-12 flex flex-col justify-start items-center border-t-gray-800 border-r-transparent border-l-transparent border-b-gray-800 border-[1.5px] mb-12"
    >
      <p class="text-2xl font-medium mb-4">YouTube video for details of this scheme.</p>
      <iframe src="https://www.youtube.com/embed/yaFzfzyIP2I" height="400" width="600" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</div>
{% endblock content %}

schemes/templates/dynamic_scheme_new.html
{% extends "base.html" %}
{% block content %}
  {% include "navbar.html" %}
  {% load custom_tags %}
  <script>
  var isPlaying = false;
  function pp() {
    var id = document.getElementById("player");
    if (isPlaying == true) {
      id.pause();
      isPlaying = false;
    } else {
      id.play();
      isPlaying = true;
      id.volume = 1.0;
    }
  }
  </script>
  <div class="flex justify-center w-full bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] h-fit">
    <div class="mt-36 w-full flex flex-col justify-start items-center">
      <div class="mb-6">
        <p class="text-center text-5xl font-[575]">{{ scheme.name }}</p>
      </div>
      <div class="mb-12 border-[1.5px] border-b-gray-800 border-t-transparent border-r-transparent border-l-transparent p-10 rounded-md w-3/4">
        <p class="text-center text-xl" name="scheme_info" id="schemee_info">{{ scheme.scheme_info }}</p>
        {% load gTTS %}
        <audio src="{% say 'en-in' hi_data %}" class="hidden" id="player" controls></audio>
        <div class="w-full flex justify-center cursor-pointer mt-6">
          <div class="text-white rounded-xl bg-blue-400 w-auto flex justify-center items-center ease-in-out px-4 py-2 font-normal text-base transition-all duration-[250ms] hover:bg-blue-700 hover:rounded-xl hover:text-white"
               onclick="pp()">
            <svg xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor"
                 class="w-6 h-6 mr-2">
              <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 18.75a6 6 0 006-6v-1.5m-6 7.5a6 6 0 01-6-6v-1.5m6 7.5v3.75m-3.75 0h7.5M12 15.75a3 3 0 01-3-3V4.5a3 3 0 116 0v8.25a3 3 0 01-3 3z"
              />
            </svg>
            <p class="cursor-pointer text-lg font-semibold">हिन्दी</p>
          </div>
        </div>
      </div>
      <div class="w-3/4 h-auto flex flex-col justify-evenly items-center border-t-transparent border-r-transparent border-l-transparent border-b-gray-800 border-[1.5px] mb-12 pb-4">
        <div class="w-1/2 flex flex-col justify-center items-center">
          <div class="-mt-8 mb-4 flex justify-center w-full items-center">
            <p class="text-3xl font-semibold">Scheme's availability and official website</p>
          </div>
          <div class="flex w-3/4 justify-around">
            <div class="w-1/2 flex flex-col justify-center items-start">
              <div class="flex">
                <p class="text-lg font-semibold mr-1">Start date :</p>
                <p class="text-lg">{{ scheme.start_date }}</p>
              </div>
              <div class="flex">
                <p class="text-lg font-semibold mr-1">End date :</p>
                <p class="text-lg">{{ scheme.last_date }}</p>
              </div>
            </div>
            <div class="w-1/2 flex flex-col">
              <a target="_blank"
                 href="{{ scheme.link }}"
                 class="text-blue-600 underline text-xl mb-1">Link to official website</a
                >
                {% if validity == "expired" %}
                  <p class="text-lg text-left font-semibold text-red-600">The scheme has been expired</p>
                {% else %}
                  <p class="text-lg text-left font-semibold text-green-600">The scheme can be availed</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="flex justify-between w-3/4 space-x-40">
          <div class="w-full h-auto">
            <div class="mb-10">
              <p class="text-4xl text-center">Eligibility critria</p>
            </div>
            <div class="rounded-lg border shadow-2xl">
              <table class="relative w-full border text-sm text-left text-black">
                <thead class="text-white">
                  <tr>
                    <th class="sticky top-0 py-3 px-6 bg-blue-600 text-md">Type</th>
                    <th class="sticky top-0 py-3 px-6 bg-blue-600 text-md">Value</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class="border-b bg-blue-200">
                    <th scope="row" class="py-4 px-6 font-medium">Age</th>
                    <td class="py-4 px-6">{{ scheme.age }}</td>
                  </tr>
                  <tr class="border-b bg-blue-300">
                    <th scope="row" class="py-4 px-6 font-medium">Marital status</th>
                    <td class="py-4 px-6">{{ scheme.marital_status }}</td>
                  </tr>
                  <tr class="border-b bg-blue-200">
                    <th scope="row" class="py-4 px-6 font-medium">Income</th>
                    <td class="py-4 px-6">
                      <ul>
                        {% for income in scheme.incomes_set.all %}<li>{{ income.income }}</li>{% endfor %}
                      </ul>
                    </td>
                  </tr>
                  <tr class="border-b bg-blue-300">
                    <th scope="row" class="py-4 px-6 font-medium">Education</th>
                    <td class="py-4 px-6">
                      <ul>
                        {% for education in scheme.educations_set.all %}<li>{{ education.education }}</li>{% endfor %}
                      </ul>
                    </td>
                  </tr>
                  <tr class="border-b bg-blue-200">
                    <th scope="row" class="py-4 px-6 font-medium">Caste</th>
                    <td class="py-4 px-6">
                      <ul>
                        {% for caste in scheme.castes_set.all %}<li>{{ caste.caste }}</li>{% endfor %}
                      </ul>
                    </td>
                  </tr>
                  <tr class="border-b bg-blue-300">
                    <th scope="row" class="py-4 px-6 font-medium">Gender</th>
                    <td class="py-4 px-6">
                      <ul>
                        {% for gender in scheme.genders_set.all %}<li>{{ gender.gender }}</li>{% endfor %}
                      </ul>
                    </td>
                  </tr>
                  <tr class="border-b bg-blue-300">
                    <th scope="row" class="py-4 px-6 font-medium">Last Date</th>
                    <td class="py-4 px-6">
                      {{ scheme.last_date }}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="w-full h-auto">
            <div class="mb-10">
              <p class="text-4xl text-center">
                Documents needed
              </p>
            </div>
            <div class="rounded-lg border shadow-2xl">
              <table class="relative w-full border text-sm text-left text-black">
                <thead>
                  <tr>
                    <th class="sticky top-0 py-3 px-6 bg-blue-600 text-xs text-white uppercase">
                      Documents
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {% for document in scheme.documents_set.all %}
                    {% if forloop.counter|divisibleby:"2" %}
                      <tr class="border-b bg-blue-200">
                        <th scope="row" class="py-4 px-6 font-medium">
                          {{ document.document }}
                        </th>
                      </tr>
                    {% else %}
                      <tr class="border-b bg-blue-300">
                        <th scope="row" class="py-4 px-6 font-medium">
                          {{ document.document }}
                        </th>
                      </tr>
                    {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="w-3/4 mt-12 h-fit py-12 flex flex-col justify-start items-center border-t-gray-800 border-r-transparent border-l-transparent border-b-gray-800 border-[1.5px] mb-12">
          <p class="text-2xl font-medium mb-4">
            YouTube video for details of this scheme.
          </p>
          <iframe src="https://www.youtube.com/embed/yaFzfzyIP2I"
                  height="400"
                  width="600"
                  frameborder="0"
                  allowfullscreen></iframe>
        </div>
      </div>
    </div>
  {% endblock content %}

schemes/templates/scheme_table1.html
<section
  class="bg-gradient-to-br from-[rgba(255,153,51,1)] via-white to-[rgba(19,136,8,1)] fixed mt-12 flex justify-center w-full h-fit overflow-y-hidden"
>
  <div class="mt-20 w-3/4 flex flex-col h-screen">
    <div class="overflow-y-auto h-3/4 rounded-lg shadow-2xl">
      <table class="relative w-full text-sm text-left text-gray-200">
        <thead>
          <tr>
            <th
              class="sticky top-0 py-3 px-6 bg-blue-600 text-md text-white uppercase"
            >
              No.
            </th>
            <th
              class="sticky top-0 py-3 px-6 bg-blue-600 text-md text-white uppercase"
            >
              Catagory
            </th>
            <th
              class="sticky top-0 py-3 px-6 bg-blue-600 text-md text-white uppercase"
            >
              Schemes
            </th>
            <th
              class="sticky top-0 py-3 px-6 bg-blue-600 text-md text-white uppercase"
            >
              Scheme info
            </th>
            <th
              class="sticky top-0 py-3 px-36 bg-blue-600 text-md text-white uppercase"
            >
              Dates
            </th>
            <th
              class="sticky top-0 py-3 px-6 bg-blue-600 text-md text-white uppercase"
            >
              Website
            </th>
            <th
              class="sticky top-0 py-3 px-20 bg-blue-600 text-md text-white uppercase"
            >
              <!-- More details -->
            </th>
          </tr>
        </thead>
        <tbody>
          {% for scheme in schemes %} {% if forloop.counter|divisibleby:"2" %}
          <tr class="border-b bg-blue-200">
            {% else %}
          </tr>

          <tr class="border-b bg-blue-300">
            {% endif %}
            <th
              scope="row"
              class="py-4 px-6 font-medium text-gray-800 whitespace-nowrap"
            >
              {{ forloop.counter }}
            </th>
            <td class="py-4 px-6 font-semibold cursor-pointer text-gray-800">
              <ul>
                {% for catagory in scheme.catagories_set.all %}
                <li>{{ catagory.catagory }}</li>
                {% endfor %}
              </ul>
            </td>
            <td class="py-4 px-6 cursor-pointer font-bold text-gray-800">
              <a
                href="{% url 'dynamic_scheme' scheme.id %}"
                class=""
                >{{ scheme.name }}</a
              >
            </td>
            <td class="py-4 px-6 cursor-pointer text-gray-800">
              {{ scheme.scheme_info }}
            </td>
            <td class="py-4 px-6 cursor-pointer text-gray-800">
              <ul>
                <div class="flex ml-12 w-full justify-start items-center">
                  <div class="mr-1">
                    <p class="font-bold">Start date:</p>
                  </div>
                  <li>{{scheme.start_date}}</li>
                </div>

                <div class="flex ml-12 w-full justify-start items-center">
                  <div class="mr-1">
                    <p class="font-bold">End date:</p>
                  </div>
                  <li>{{scheme.last_date}}</li>
                </div>
              </ul>
            </td>
            <td class="py-4 px-6 cursor-pointer text-gray-800">
              {% if scheme.is_past_due %}
              <a>
                <div class="mt-5">
                  <button
                    class="w-auto text-gray-50 transition-all duration-[250ms] bg-blue-600 opacity-50 focus:outline-none font-normal rounded-lg text-sm px-4 py-2 text-center"
                  >
                    Apply
                  </button>
                  <div class="flex w-full mt-1 justify-center items-center">
                    <p class="text-red-600 font-bold text-xs">Expired</p>
                  </div>
                </div>
              </a>
              {% else %}
              <a href="{{scheme.link}}">
                <button
                  class="w-auto text-gray-50 transition-all duration-[250ms] bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none font-normal rounded-lg text-sm px-4 py-2 text-center"
                >
                  Apply
                </button>
                <!-- <p class="mt-2 text-xs text-blue-700">View more</p> -->
              </a>
              {% endif %}
            </td>
            <td class="py-4 px-6 cursor-pointer text-gray-800">
              <div class="flex items-center h-auto justify-center w-full">
                <!-- <button
                class="w-auto text-gray-50 transition-all duration-[250ms] bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none font-normal rounded-lg text-sm px-4 py-2 text-center"
              > -->
              <a
                href="{% url 'dynamic_scheme' scheme.id %}"
                class="text-blue-700 underline"
                >View more</a
              >
                
              <!-- </button> -->
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

schemes/templates/user_schemes.html
{% extends 'base.html' %}
{% block content %}
    {% include 'navbar.html' %}
    {% include "user_scheme_table.html" %}
{% endblock content %}